# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twiter: &default_twitter
 twitter_api_key: 'A6vni4Ha2TWUvpNgp4sHSLVWy'
 twitter_api_secret: 'JYu6RdhwlyDTH3F1X7X7U9O6vh0ZKdvuqYoyuBwfA900ApVFAx'

development:
  secret_key_base: 8fcec96c1422d03699dccd22f3a2451d953fc472017178b98bacdb69717579cca7da361ad1f2238c6bbe97a13816d6655cc2a883d0c1137699a051746daa38a0
  <<: *default_twitter

test:
  secret_key_base: 19febee5f706be9dea3a59ef19057eb2b2dc10bf1e06ad50b663429a333b56e352c18ccf1b15791bf61a9fb070866658d57e6c7ad472597beeeb261c99049966
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"]
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"]